# Generated by Django 4.1.4 on 2024-06-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
