# Generated by Django 4.1.4 on 2024-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_department_password_alter_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('orange', 'Orange'), ('indigo', 'Indigo'), ('green', 'Green'), ('purple', 'Purple')], max_length=250, null=True),
        ),
    ]
