# Generated by Django 4.1.4 on 2024-06-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_department_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='department_profile',
            field=models.ImageField(blank=True, default='images/Departmentdefault.svg', null=True, upload_to='images/departments'),
        ),
    ]
