# Generated by Django 4.1.4 on 2024-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_activity_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('not_done', 'Not Done')], default='not_done', max_length=250, null=True),
        ),
    ]
