# Generated by Django 4.1.4 on 2024-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_institutionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionrequest',
            name='request_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
